package com.paulstna.springsecurityapp.audit.enums;

public enum FailureReason {
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,

    TOKEN_REQUIRED,
    INVALID_TOKEN,
    TOKEN_OWNERSHIP_MISMATCH,

    INSUFFICIENT_PRIVILEGES,
    RATE_LIMIT_EXCEEDED,

    INVALID_STATE,
    UNEXPECTED_ERROR,
    SYSTEM_ERROR
}
